Repository eclipse-edc/GradlePlugins, pull requests merged in 2022-09, with the labels that each got.

#1 refactor: move edc runtime metamodel here
  autodoc/build.gradle.kts
  autodoc/build/tmp/compileJava/previous-compilation-data.bin
  autodoc/src/test/java/org/eclipse/dataspaceconnector/plugins/AutodocPluginTest.java
  build.gradle.kts
  gradle.properties
  runtime-metamodel/build.gradle.kts
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/BaseExtension.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/CoreExtension.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/EdcSetting.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/EdcSettingContext.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/Extension.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/ExtensionPoint.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/Inject.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/Provider.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/Provides.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/Requires.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/Spi.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/domain/ConfigurationSetting.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/domain/EdcModule.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/domain/ModuleType.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/domain/Service.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/domain/ServiceReference.java
  runtime-metamodel/src/test/java/org/eclipse/dataspaceconnector/tooling/autodoc/domain/ConfigurationSettingTest.java
  runtime-metamodel/src/test/java/org/eclipse/dataspaceconnector/tooling/autodoc/domain/EdcModuleTest.java
  runtime-metamodel/src/test/java/org/eclipse/dataspaceconnector/tooling/autodoc/domain/ServiceReferenceTest.java
  runtime-metamodel/src/test/java/org/eclipse/dataspaceconnector/tooling/autodoc/domain/ServiceTest.java
  settings.gradle.kts
Labels: enhancement

#3 feat(build): create release pipeline for `runtime-metamodel`
  .github/release.yaml
  .github/workflows/release-runtime-metamodel.yml
  build.gradle.kts
  gradle.properties
  runtime-metamodel/build.gradle.kts
Labels: build

#5 fix: use correct urls, apply group and version to all projects
  autodoc/build.gradle.kts
  build.gradle.kts
  gradle.properties
Labels: bug

#8 feat: implement autodoc plugin
  plugins/autodoc/autodoc-extension-test/build.gradle.kts
  plugins/autodoc/autodoc-plugin/README.md
  plugins/autodoc/autodoc-plugin/build.gradle.kts
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/AutodocDependencyInjector.java
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/AutodocExtension.java
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/AutodocPlugin.java
  plugins/autodoc/autodoc-processor/README.md
  plugins/autodoc/autodoc-processor/build.gradle.kts
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/EdcModuleProcessor.java
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/compiler/AnnotationBooleanValueResolver.java
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/compiler/AnnotationClassValuesResolver.java
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/compiler/AnnotationFunctions.java
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/compiler/AnnotationLongValueResolver.java
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/compiler/AnnotationStringValueResolver.java
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/compiler/AnnotationStringValuesResolver.java
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/compiler/ElementFunctions.java
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/compiler/VariableTypeResolver.java
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/generator/JavadocConverter.java
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/introspection/ModuleIntrospector.java
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/introspection/OverviewIntrospector.java
  plugins/autodoc/autodoc-processor/src/main/resources/META-INF/gradle/incremental.annotation.processors
  plugins/autodoc/autodoc-processor/src/main/resources/META-INF/services/javax.annotation.processing.Processor
  plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/compiler/AnnotationFunctionsTest.java
  plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/compiler/ElementFunctionsTest.java
  plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/compiler/MockBooleanValue.java
  plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/compiler/MockCollectionValues.java
  plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/compiler/MockStringValue.java
  plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/compiler/MockTypeMirror.java
  plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/dataspaceconnector/plugins/autodoc/core/processor/compiler/MockTypeValue.java
  plugins/autodoc/autodoc-spi-test/build.gradle.kts
  settings.gradle.kts
Labels: build

#11 feat: enable publishing of plugin snapshots
  .github/workflows/release-autodoc-plugin.yml
  build.gradle.kts
  plugins/autodoc/autodoc-plugin/build.gradle.kts
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/AutodocDependencyInjector.java
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/dataspaceconnector/plugins/autodoc/AutodocPlugin.java
Labels: enhancement

#12 docs: add documentation for autodoc
  docs/developer/autodoc.md
Labels: documentation

#7 chore: add basic documents
  CODEOWNERS
  CONTRIBUTING.md
  LICENSE
  SECURITY.md
Labels: documentation

#10 chore(Documentation): apply @Documented to EDC annotations
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/BaseExtension.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/CoreExtension.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/EdcSetting.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/Inject.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/Provider.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/Provides.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/Requires.java
  runtime-metamodel/src/main/java/org/eclipse/dataspaceconnector/runtime/metamodel/annotation/Spi.java
Labels: documentation
