Repository eclipse-edc/GradlePlugins, pull requests merged in 2022-11, with the labels that each got.

#36 fix(doc): add NOTICE.md file to JAR
  NOTICE.md
  build.gradle.kts
  docs/legal/generateThirdPartyReport.sh
Labels: bug, documentation

#38 feat(build): add and publish a version catalog
  build.gradle.kts
  gradle/libs.versions.toml
  settings.gradle.kts
  version-catalog/build.gradle.kts
Labels: build

#39 feat(build): read default versions from version catalog
  gradle/libs.versions.toml
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/DefaultDependencyConvention.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/extensions/VersionsExtension.java
Labels: build

#43 fix: apply nexus convention during the config phase
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/EdcBuildPlugin.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/DefaultDependencyConvention.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/NexusPublishingConvention.java
Labels: bug

#42 feat(build): add apiGroup to config
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/SwaggerGeneratorConvention.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/extensions/SwaggerGeneratorExtension.java
  plugins/edc-build/src/test/java/org/eclipse/edc/plugins/edcbuild/conventions/SwaggerGeneratorConventionTest.java
Labels: build

#45 feat: create custom merger task
  plugins/edc-build/build.gradle.kts
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/EdcBuildBasePlugin.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/EdcBuildPlugin.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/ConventionFunctions.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/SwaggerGeneratorConvention.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/tasks/PrintApiGroupTask.java
  plugins/openapi-merger/README.md
  plugins/openapi-merger/build.gradle.kts
  plugins/openapi-merger/src/main/java/org/eclipse/edc/plugins/openapimerger/OpenApiMergerPlugin.java
  plugins/openapi-merger/src/main/java/org/eclipse/edc/plugins/openapimerger/tasks/MergeApiSpecByPathTask.java
  plugins/openapi-merger/src/test/java/org/eclipse/edc/plugins/modulenames/OpenApiMergerPluginTest.java
  settings.gradle.kts
Labels: build

#47 chore: remove @EdcSetting and @EdcSettingContext from the code base
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/edc/plugins/autodoc/core/processor/introspection/ExtensionIntrospector.java
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/edc/plugins/autodoc/core/processor/introspection/ModuleIntrospector.java
  plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/edc/plugins/autodoc/core/processor/testextensions/SampleExtensionWithoutAnnotation.java
  runtime-metamodel/src/main/java/org/eclipse/edc/runtime/metamodel/annotation/EdcSetting.java
  runtime-metamodel/src/main/java/org/eclipse/edc/runtime/metamodel/annotation/EdcSettingContext.java
Labels: enhancement

#49 fix: explicitly exclude annotation processors from dep-analysis
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocDependencyInjector.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/DependencyAnalysisConvention.java
Labels: bug

#53 feat: add defaultValue to `@Setting`
  runtime-metamodel/src/main/java/org/eclipse/edc/runtime/metamodel/annotation/Setting.java
  settings.gradle.kts
Labels: enhancement

#55 fix: Revert "chore: remove @EdcSettng and @EdcSettingContext from the…
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/edc/plugins/autodoc/core/processor/introspection/ExtensionIntrospector.java
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/edc/plugins/autodoc/core/processor/introspection/ModuleIntrospector.java
  plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/edc/plugins/autodoc/core/processor/testextensions/SampleExtensionWithoutAnnotation.java
  runtime-metamodel/src/main/java/org/eclipse/edc/runtime/metamodel/annotation/EdcSetting.java
  runtime-metamodel/src/main/java/org/eclipse/edc/runtime/metamodel/annotation/EdcSettingContext.java
Labels: bug

#56 build: add workflow to explicitly trigger Jenkins
  .github/workflows/trigger_snapshot.yml
Labels: enhancement
