Repository eclipse-edc/GradlePlugins, pull requests merged in 2022-12, with the labels that each got.

#61 feat(workflows): add discord webhook for issues, discussions and pull requests
  .github/workflows/discord-webhook.yml
Labels: no-changelog

#62 build(deps): update nimbus to v9 to combat transitive dependency clashes
  gradle/libs.versions.toml
Labels: build, dependencies

#63 build: upgrade Gradle to version 7.6
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: build

#65 build(deps): Add bouncycastle jdk18on version
  .github/ISSUE_TEMPLATE/adoption_request.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  gradle/libs.versions.toml
Labels: dependencies
