Repository eclipse-edc/GradlePlugins, pull requests merged in 2023-11, with the labels that each got.

#190 build: remove fraunhofer repository as it is not needed anymore
  DEPENDENCIES
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/RepositoriesConvention.java
Labels: build

#192 feat(autodoc): suppoort context property on autodoc
  DEPENDENCIES
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/edc/plugins/autodoc/core/processor/introspection/ExtensionIntrospector.java
  plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/edc/plugins/autodoc/core/processor/Constants.java
  plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/edc/plugins/autodoc/core/processor/EdcModuleProcessorExtensionTest.java
  plugins/autodoc/autodoc-processor/src/test/java/org/eclipse/edc/plugins/autodoc/core/processor/testextensions/SettingContextExtension.java
Labels: enhancement

#196 build: cleanup ci workflows
  .github/workflows/close-inactive-issues.yml
  .github/workflows/discord-webhook.yml
  .github/workflows/first-interaction.yml
  .github/workflows/release-all-java.yml
  .github/workflows/scan-pull-request.yaml
  .github/workflows/stale-bot.yml
  DEPENDENCIES
Labels: build, refactoring
