Repository eclipse-edc/GradlePlugins, pull requests merged in 2023-03, with the labels that each got.

#90 fix: let users set the group id
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/MavenPublicationConvention.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/extensions/MavenPomExtension.java
Labels: build

#100 feat: allow adding a repository to publish via CLI parameters
  plugins/edc-build/README.md
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/MavenPublishingConvention.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/NexusPublishingConvention.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/Repositories.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/extensions/BuildExtension.java
Labels: enhancement

#105 fix: Revert "chore: upgrade to Gradle 8.0 (#89)"
  gradle/wrapper/gradle-wrapper.properties
  plugins/autodoc/autodoc-plugin/build.gradle.kts
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocDependencyInjector.java
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocPlugin.java
  plugins/edc-build/build.gradle.kts
  plugins/module-names/build.gradle.kts
  plugins/openapi-merger/build.gradle.kts
  plugins/test-summary/build.gradle.kts
Labels: bug

#106 fix: Revert "chore: upgrade to Gradle 8.0 (#89)" (#105)
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  plugins/autodoc/autodoc-plugin/build.gradle.kts
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocDependencyInjector.java
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocPlugin.java
  plugins/edc-build/build.gradle.kts
  plugins/module-names/build.gradle.kts
  plugins/openapi-merger/build.gradle.kts
  plugins/test-summary/build.gradle.kts
Labels: bug

#107 refactor: cleanup build file
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/gradle.properties
  buildSrc/settings.gradle.kts
  gradle.properties
  gradle/libs.versions.toml
  plugins/autodoc/autodoc-plugin/README.md
  plugins/autodoc/autodoc-plugin/build.gradle.kts
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocDependencyInjector.java
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocExtension.java
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocPlugin.java
  plugins/autodoc/autodoc-processor/build.gradle.kts
  plugins/edc-build/build.gradle.kts
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/EdcBuildPlugin.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/DefaultDependencyConvention.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/SigningConvention.java
  plugins/module-names/build.gradle.kts
  plugins/openapi-merger/build.gradle.kts
  plugins/test-summary/build.gradle.kts
  runtime-metamodel/build.gradle.kts
Labels: refactoring

#109 fix: annotation processor injector
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocDependencyInjector.java
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocPlugin.java
Labels: bug

#116 fix: use gradle 'group' property instead of 'groupId'
  build.gradle.kts
  gradle.properties
  plugins/autodoc/autodoc-plugin/build.gradle.kts
  plugins/edc-build/README.md
  plugins/edc-build/build.gradle.kts
  plugins/module-names/build.gradle.kts
  plugins/openapi-merger/build.gradle.kts
  plugins/test-summary/build.gradle.kts
Labels: build

#119 fix: supply Jackson Dataformat XML libs alongside azure
  gradle/libs.versions.toml
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/DefaultDependencyConvention.java
Labels: bug
