Repository eclipse-edc/GradlePlugins, pull requests merged in 2023-05, with the labels that each got.

#156 build(deps): bump swagger-gradle-plugins to 2.2.10
  gradle/libs.versions.toml
Labels: dependencies

#159 build: switch default java version to 17
  build.gradle.kts
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/JavaConvention.java
Labels: enhancement, build

#160 build: update annotation processor source version to 17
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/edc/plugins/autodoc/core/processor/EdcModuleProcessor.java
Labels: build

#161 chore: add job to bump version on GH release
  .github/actions/bump-version/action.yml
  .github/workflows/release-all-java.yml
  .github/workflows/release-gradle-plugins.yml
  .github/workflows/release-runtime-metamodel.yml
Labels: build

#162 chore: update snapshot version to 0.1.0-SNAPSHOT
  buildSrc/gradle.properties
  docs/legal/generateThirdPartyReport.sh
  gradle.properties
  plugins/autodoc/autodoc-plugin/build.gradle.kts
  plugins/edc-build/build.gradle.kts
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/DefaultDependencyConvention.java
  plugins/module-names/build.gradle.kts
  plugins/openapi-merger/build.gradle.kts
  plugins/test-summary/build.gradle.kts
Labels: build
