Repository eclipse-edc/GradlePlugins, pull requests merged in 2023-04, with the labels that each got.

#127 fix: avoid NPE on DefaultDependencyConvention
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/DefaultDependencyConvention.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/MavenPublicationConvention.java
Labels: bug, build

#140 chore: remove unused gatling dependency
  gradle/libs.versions.toml
  plugins/autodoc/autodoc-processor/src/main/java/org/eclipse/edc/plugins/autodoc/core/processor/EdcModuleProcessor.java
Labels: refactoring, dependencies

#148 build: cleanup version catalog
  gradle/libs.versions.toml
Labels: build, refactoring, dependencies

#151 feat: set pom information defaults
  build.gradle.kts
  gradle.properties
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/MavenArtifactConvention.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/extensions/MavenPomExtension.java
Labels: build

#154 fix: re-add setter for grouId in the MavenPomExtension
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/extensions/MavenPomExtension.java
Labels: bug
