Repository eclipse-edc/GradlePlugins, pull requests merged in 2023-01, with the labels that each got.

#74 refactor: format settings.gradle.kts
  settings.gradle.kts
Labels: refactoring

#75 chore: add publish flag
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/extensions/BuildExtension.java
Labels: enhancement

#67 feat: add Maven publication convention
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/EdcBuildPlugin.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/Conventions.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/MavenPublicationConvention.java
Labels: enhancement, build

#76 build(deps): bump aws-sdk-java-v2 to 2.19.26
  gradle/libs.versions.toml
Labels: build, dependencies
