Repository eclipse-edc/GradlePlugins, pull requests merged in 2023-08, with the labels that each got.

#166 feat: add manifest-to-markdown renderer
  DEPENDENCIES
  buildSrc/build.gradle.kts
  gradle/libs.versions.toml
  plugins/autodoc/autodoc-converters/README.md
  plugins/autodoc/autodoc-converters/build.gradle.kts
  plugins/autodoc/autodoc-converters/src/main/java/org/eclipse/edc/plugins/autodoc/json/JsonManifestReader.java
  plugins/autodoc/autodoc-converters/src/main/java/org/eclipse/edc/plugins/autodoc/markdown/MarkdownManifestRenderer.java
  plugins/autodoc/autodoc-converters/src/main/java/org/eclipse/edc/plugins/autodoc/spi/ManifestConverterException.java
  plugins/autodoc/autodoc-converters/src/main/java/org/eclipse/edc/plugins/autodoc/spi/ManifestReader.java
  plugins/autodoc/autodoc-converters/src/main/java/org/eclipse/edc/plugins/autodoc/spi/ManifestRenderer.java
  plugins/autodoc/autodoc-converters/src/main/java/org/eclipse/edc/plugins/autodoc/spi/ManifestWriter.java
  plugins/autodoc/autodoc-converters/src/test/java/org/eclipse/edc/plugins/autodoc/json/JsonManifestReaderTest.java
  plugins/autodoc/autodoc-converters/src/test/java/org/eclipse/edc/plugins/autodoc/markdown/MarkdownManifestRendererTest.java
  plugins/autodoc/autodoc-converters/src/test/resources/example_manifest.json
  plugins/autodoc/autodoc-converters/src/test/resources/invalid_manifest.json
  plugins/autodoc/autodoc-converters/src/test/resources/simple_manifest.json
  plugins/autodoc/autodoc-plugin/build.gradle.kts
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocPlugin.java
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/JsonFileAppender.java
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/MarkdownRendererTask.java
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/MergeManifestsTask.java
  settings.gradle.kts
Labels: documentation, enhancement

#167 feat: download transitive autodoc manifests
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocExtension.java
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/AutodocPlugin.java
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/ManifestDownloadTask.java
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/MarkdownRendererTask.java
  plugins/autodoc/autodoc-plugin/src/main/java/org/eclipse/edc/plugins/autodoc/tasks/MergeManifestsTask.java
  plugins/autodoc/autodoc-plugin/src/test/java/org/eclipse/edc/plugins/autodoc/AutodocPluginTest.java
Labels: enhancement

#171 refactor: remove dependency analysis plugin
  DEPENDENCIES
  buildSrc/build.gradle.kts
  gradle/libs.versions.toml
  plugins/edc-build/build.gradle.kts
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/EdcBuildBasePlugin.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/EdcBuildPlugin.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/AllDependenciesConvention.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/Conventions.java
  plugins/edc-build/src/main/java/org/eclipse/edc/plugins/edcbuild/conventions/DependencyAnalysisConvention.java
Labels: refactoring

#173 fix: update dependencies
  DEPENDENCIES
Labels: dependencies

#175 build: update release.yaml
  .github/release.yaml
  DEPENDENCIES
Labels: build
